trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  sshServiceConnection: 'L4D2 - Server'

stages:
- stage: Deploy
  jobs:
  - job: DeployFromGit
    steps:
    - task: SSH@0
      inputs:
        sshEndpoint: $(sshServiceConnection)
        readyTimeout: '20000'
        commands: |
          # Clone the GitHub repository into /home/github
          rm -rf /home/github/l4d2-zone-server
          git clone https://github.com/altair-sossai/l4d2-zone-server.git /home/github/l4d2-zone-server

          # Copy folders to the destination without deleting existing files
          cp -r /home/github/l4d2-zone-server/addons/* /home/steam/l4d2/left4dead2/addons/
          cp -r /home/github/l4d2-zone-server/cfg/* /home/steam/l4d2/left4dead2/cfg/
          cp -r /home/github/l4d2-zone-server/bash/* /home/steam/l4d2/left4dead2/bash/
          cp -r /home/github/l4d2-zone-server/scripts/* /home/steam/l4d2/left4dead2/scripts/

          # Copy text files
          cp /home/github/l4d2-zone-server/host.txt /home/steam/l4d2/left4dead2/host.txt
          cp /home/github/l4d2-zone-server/motd.txt /home/steam/l4d2/left4dead2/motd.txt

          # Convert line endings and set executable permissions for bash scripts
          dos2unix /home/steam/l4d2/left4dead2/bash/*.sh > /dev/null 2>&1
          chmod +x /home/steam/l4d2/left4dead2/bash/*.sh

          # Clean up the cloned repository
          rm -rf /home/github/l4d2-zone-server
