trigger:
- master

pool:
  vmImage: 'ubuntu-latest'

variables:
  sshServiceConnection: 'L4D2'

stages:
- stage: Deploy
  jobs:
  - job: UploadAddons
    steps:
    - task: CopyFilesOverSSH@0
      inputs:
        sshEndpoint: $(sshServiceConnection)
        sourceFolder: '$(Build.Repository.LocalPath)/cfg'
        contents: '**'
        targetFolder: '/home/devops'
        cleanTargetFolder: false
        overwrite: true