spcomp ..\addons\sourcemod\scripting\alltalk-before-round-start.sp -o ..\addons\sourcemod\plugins\optional\alltalk-before-round-start.smx
spcomp ..\addons\sourcemod\scripting\l4d2_queue.sp -o ..\addons\sourcemod\plugins\optional\l4d2_queue.smx
spcomp ..\addons\sourcemod\scripting\l4d2_mix.sp -o ..\addons\sourcemod\plugins\optional\l4d2_mix.smx
spcomp ..\addons\sourcemod\scripting\l4d2_spectating_cheat.sp -o ..\addons\sourcemod\plugins\optional\l4d2_spectating_cheat.smx
spcomp ..\addons\sourcemod\scripting\l4d2_connect_announce.sp -o ..\addons\sourcemod\plugins\optional\l4d2_connect_announce.smx
spcomp ..\addons\sourcemod\scripting\l4d2_tank_is_comming.sp -o ..\addons\sourcemod\plugins\optional\l4d2_tank_is_comming.smx
spcomp ..\addons\sourcemod\scripting\l4d_death_item_glow.sp -o ..\addons\sourcemod\plugins\optional\l4d_death_item_glow.smx
spcomp ..\addons\sourcemod\scripting\l4d2_playstats_sync.sp -o ..\addons\sourcemod\plugins\optional\l4d2_playstats_sync.smx
spcomp ..\addons\sourcemod\scripting\l4d2_ranking.sp -o ..\addons\sourcemod\plugins\optional\l4d2_ranking.smx
spcomp ..\addons\sourcemod\scripting\l4d2_show_patent_icon.sp -o ..\addons\sourcemod\plugins\optional\l4d2_show_patent_icon.smx
spcomp ..\addons\sourcemod\scripting\l4d2_no_skip_getup_animation.sp -o ..\addons\sourcemod\plugins\optional\l4d2_no_skip_getup_animation.smx
spcomp ..\addons\sourcemod\scripting\l4d2_gameinfo_sync.sp -o ..\addons\sourcemod\plugins\l4d2_gameinfo_sync.smx